Get sysfs and procfs data from remote mysql server with I_S.procfs
percona/node_exporter pull request #8
Opened 2019-01-18 08:27 UTC by ihanick

Fetches sysfs and procfs files contents from remote mysql servers via https://github.com/Percona-Lab/procfs and stores these files in -collector.procfs and -collector.sysfs directories before parsing

https://jira.percona.com/browse/PMM-7593

2019-01-18 08:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/signed)](https://cla-assistant.percona.com:443/percona/node_exporter?pullRequest=8) <br/>All committers have signed the CLA.

2021-06-02 10:52 UTC, percona-csalguero requested changes
Could you please fix the conflicts?
There are a lot of merge conflics and we are using go.mod files.
Also, what happens if the profs plugin/metrics are not available? The exporter is throwing an error on every scrape.
Please fix the conflicts and make it pass a `make` in order to be able to test.
Thanks

2021-08-30 07:37 UTC, JiriCtvrtka submitted a review, later dismissed

2021-08-30 13:56 UTC, ihanick commented
> Could you please fix the conflicts? There are a lot of merge conflics and we are using go.mod files.
done

> Also, what happens if the profs plugin/metrics are not available?
The plugin is activated only if collector.mysqlprocfs command line argument with mysql DSN is provided.
If a procfs plugin is not available on mysql side or DSN is invalid a warning generated.

> The exporter is throwing an error on every scrape.
Remote MySQL daemon could be restarted/mysql settings  changed. In addition it's possible to have out of disk space issue or other filesystem problems. 

Should I implement a global map with counters and show a specific error only once/every N errors of the same type?

> Please fix the conflicts and make it pass a `make` in order to be able to test.
done

2021-08-30 16:41 UTC, percona-csalguero approved these changes

2021-08-31 06:39 UTC, JiriCtvrtka approved these changes

2021-09-10 06:12 UTC, LenzGr commented
FYI, the procfs code has been merged and is included in PS since version 8.0.25: https://github.com/percona/percona-server/pull/4251

2024-10-06 09:20 UTC, closed without merging